name: Maven Package, Docker image publish and verify

on:
  push:
    branches:
     - main

jobs:
  maven:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml

    - name: Build with Maven
      run: mvn -B package
    - name: Upload artifact for Docker job
      uses: actions/upload-artifact@v3
      with:
        name: java-app
        path: '${{ github.workspace }}/target/*.jar'

  docker-publish:

    runs-on: ubuntu-latest
    needs: maven
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
    - name: Download artifact from maven job
      uses: actions/download-artifact@v3
      with:
        name: java-app

    - name: Docker login
      run: docker login ghcr.io -u kovacsd -p ${{ github.token }}
    - name: Build Docker image
      run: docker build . -t ghcr.io/kovacsd/cubix/1/homework/app:springboot
    - name: Publish Docker image
      run: docker push ghcr.io/kovacsd/cubix/1/homework/app:springboot

  docker-verify:

    runs-on: ubuntu-latest
    needs: docker-publish
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v3
    - name: verify docker image
      run: ./verify-image.sh
